### Crear departamento
POST http://localhost:3000/api/departments/post
Content-Type: application/json

{
  "nombre": "Recepcion"
}

###

### Listar departamentos
GET http://localhost:3000/api/departments/get

###

### Obtener departamento por ID
GET http://localhost:3000/api/departments/get/1

###

### Actualizar departamento
PUT http://localhost:3000/api/departments/put/1
Content-Type: application/json

{
  "nombre": "Recursos Humanos"
}

###

### Eliminar departamento
DELETE http://localhost:3000/api/departments/delete/5
