### Crear estado de dispositivo
POST http://localhost:3000/api/device-status/post
Content-Type: application/json

{
  "nombre": "Baja"
}

###

### Listar estados
GET http://localhost:3000/api/device-status/get

###

### Obtener estado por ID
GET http://localhost:3000/api/device-status/get/1

###

### Actualizar estado
PUT http://localhost:3000/api/device-status/put/2
Content-Type: application/json

{
  "nombre": "En reparación"
}

###

### Eliminar estado
DELETE http://localhost:3000/api/device-status/delete/1
