### 🚀 Crear baja
POST http://localhost:3000/api/disposals/post
Content-Type: application/json

{
  "motivo": "Equipo obsoleto",
  "observaciones": "Ya no enciende",
  "fecha_baja": "2025-09-01T09:00:00Z",
  "deviceId": 8
}

###

### 📋 Listar todas las bajas
GET http://localhost:3000/api/disposals/get

###

### 🔎 Obtener baja por ID
GET http://localhost:3000/api/disposals/get/1

###

### ✏️ Actualizar baja
PUT http://localhost:3000/api/disposals/put/1
Content-Type: application/json

{
  "motivo": "Donación",
  "observaciones": "Equipo donado a otra área",
  "fecha_baja": "2025-09-02T12:00:00Z"
}

###

### 🗑️ Eliminar baja
DELETE http://localhost:3000/api/disposals/delete/2

###

### 📤 Exportar bajas a Excel
GET http://localhost:3000/api/disposals
