### Crear mantenimiento
POST http://localhost:3000/api/maintenances/post
Content-Type: application/json

{
  "descripcion": "Cambio de disco duro",
  "fecha_programada": "2025-09-15T10:00:00Z",
  "deviceId": 5,
  "proveedor": "ProveedorX"
}

###

### Listar mantenimientos
GET http://localhost:3000/api/maintenances/get

###

### Obtener mantenimiento por ID
GET http://localhost:3000/api/maintenances/get/1

###

### Actualizar mantenimiento
PUT http://localhost:3000/api/maintenances/put/1
Content-Type: application/json

{
  "estado": "realizado",
  "fecha_realizacion": "2025-09-20T12:00:00Z"
}

###

### Eliminar mantenimiento
DELETE http://localhost:3000/api/maintenances/delete/2
