### Crear sistema operativo
POST http://localhost:3000/api/operating-systems/post
Content-Type: application/json

{
  "nombre": "Windows 11 Pro"
}

###

### Listar sistemas operativos
GET http://localhost:3000/api/operating-systems/get

###

### Obtener SO por ID
GET http://localhost:3000/api/operating-systems/get/1

###

### Actualizar sistema operativo
PUT http://localhost:3000/api/operating-systems/put/2
Content-Type: application/json

{
  "nombre": "Ubuntu 22.04"
}

###

### Eliminar sistema operativo
DELETE http://localhost:3000/api/operating-systems/delete/2
