### Crear usuario
POST http://localhost:3000/api/users/post
Content-Type: application/json

{
  "nombre": "EduardoM",
  "correo": "laMo@example.com",
  "departamentoId": 5,
  "ip_equipo": "192.168.1.142",
  "usuario_login": "lLOU",
  "password_login": "123456"
}

###

### Listar usuarios
GET http://localhost:3000/api/users/get

###

### Obtener usuario por ID
GET http://localhost:3000/api/users/get/1

###

### Actualizar usuario
PUT http://localhost:3000/api/users/put/1
Content-Type: application/json

{
  "ip_equipo": "192.168.1.11"
}

###

### Eliminar usuario
DELETE http://localhost:3000/api/users/delete/1
